name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run compile
    
    - name: Package extension
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      run: |
        npm install -g vsce
        vsce package
    
    - name: Upload artifact
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      uses: actions/upload-artifact@v3
      with:
        name: vscode-extension
        path: '*.vsix'